### PR TITLE
Add an upgrade guide to the documentation

### PR DESCRIPTION
**Pull request by rowild**
Add upgrade guide as discussed here: #7

### CODE REVIEW

**Comment by rowild** [comment]
I have no idea why this PR shows other commits from 4 months ago...

**Comment by rowild** [comment]
In a commit I wrote:

The upgrade guide tries to cover as many steps as possible, at least those I encountered during the update. Is there anything I didn't think of? Or do you think those are too many?

Please let me know! Thanks!

**Comment by gilbertsoft** [comment]
> 
> 
> I have no idea why this PR shows other commits from 4 months ago... I forked the repo anew and created a dedicated branch for this commit. However, it seems that I did something wrong. If this causes any troubles, let me know and I provide a new PR.
> 
> Set to "In progress" for the moment.

Did you also delete your local clone? If you remove the fork the new one should be up to date with the upstream. And since some time there is a new feature at GH to synchronize your existing fork with the upstream:

grafik

But it looks this should not be an issue, no changes are shown from the previous commits.

**Comment by rowild** [comment]
Thinking out loud: Reading through the TYPO3 and the ddev docs I observe that the public folder is usually called just that: `public`. This repo, however, uses `htdocs`. I was wondering if going along with the more-or-less standard naming conventions wouldn't be better?

**Comment by gilbertsoft** [comment]
> 
> 
> Thinking out loud: Reading through the TYPO3 and the ddev docs I observe that the public folder is usually called just that: `public`. This repo, however, uses `htdocs`. I was wondering if going along with the more-or-less standard naming conventions wouldn't be better?

I've called it `htdocs` back then because many cheap hosters name it like this. But you can simply change it in the config.yaml, the install script reads that path from the environment variable.

**Pull request merged**
